kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    architectures:
      - "ppc64le"
    channels:
    - name: stable-4.20
      minVersion: 4.20.2
      maxVersion: 4.20.2
